ruby ../src/convert.rb --check modules/AddOnProduct.xml
ruby ../src/convert.rb --check modules/Address.xml
ruby ../src/convert.rb --check modules/Arch.xml
ruby ../src/convert.rb --check modules/AsciiFile.xml
ruby ../src/convert.rb --check modules/AutoInstallRules.xml
ruby ../src/convert.rb --check modules/AutoInstall.xml
ruby ../src/convert.rb --check modules/AutoinstClass.xml
ruby ../src/convert.rb --check modules/AutoinstClone.xml
ruby ../src/convert.rb --check modules/AutoinstConfig.xml
ruby ../src/convert.rb --check modules/AutoinstFile.xml
ruby ../src/convert.rb --check modules/AutoinstGeneral.xml
ruby ../src/convert.rb --check modules/AutoinstImage.xml
ruby ../src/convert.rb --check modules/AutoinstLVM.xml
ruby ../src/convert.rb --check modules/AutoinstRAID.xml
ruby ../src/convert.rb --check modules/AutoinstScripts.xml
ruby ../src/convert.rb --check modules/AutoinstSoftware.xml
ruby ../src/convert.rb --check modules/AutoinstStorage.xml
ruby ../src/convert.rb --check modules/AutoinstX11.xml
ruby ../src/convert.rb --check modules/Autologin.xml
ruby ../src/convert.rb --check modules/AutoOnlineUpdate.xml
ruby ../src/convert.rb --check modules/Backup.xml
ruby ../src/convert.rb --check modules/Bluetooth.xml
ruby ../src/convert.rb --check modules/BootArch.xml
ruby ../src/convert.rb --check modules/BootCommon.xml
ruby ../src/convert.rb --check modules/BootELILO.xml
ruby ../src/convert.rb --check modules/BootGRUB.xml
ruby ../src/convert.rb --check modules/BootLILO.xml
ruby ../src/convert.rb --check modules/Bootloader.xml
ruby ../src/convert.rb --check modules/BootPOWERLILO.xml
ruby ../src/convert.rb --check modules/BootZIPL.xml
ruby ../src/convert.rb --check modules/Call.xml
ruby ../src/convert.rb --check modules/CheckMedia.xml
ruby ../src/convert.rb --check modules/CommandLine.xml
ruby ../src/convert.rb --check modules/Confirm.xml
ruby ../src/convert.rb --check modules/Console.xml
ruby ../src/convert.rb --check modules/Crash.xml
ruby ../src/convert.rb --check modules/Cron.xml
ruby ../src/convert.rb --check modules/CUPS.xml
ruby ../src/convert.rb --check modules/CustomDialogs.xml
ruby ../src/convert.rb --check modules/CWMFirewallInterfaces.xml
ruby ../src/convert.rb --check modules/CWMServiceStart.xml
ruby ../src/convert.rb --check modules/CWMTab.xml
ruby ../src/convert.rb --check modules/CWMTsigKeys.xml
ruby ../src/convert.rb --check modules/CWM.xml
ruby ../src/convert.rb --check modules/DefaultDesktop.xml
ruby ../src/convert.rb --check modules/Desktop.xml
ruby ../src/convert.rb --check modules/Detection.xml
ruby ../src/convert.rb --check modules/DhcpServerUI.xml
ruby ../src/convert.rb --check modules/DialogTree.xml
ruby ../src/convert.rb --check modules/Directory.xml
ruby ../src/convert.rb --check modules/DirInstall.xml
ruby ../src/convert.rb --check modules/DnsFakeTabs.xml
ruby ../src/convert.rb --check modules/DnsServerUI.xml
ruby ../src/convert.rb --check modules/DNS.xml
ruby ../src/convert.rb --check modules/DontShowAgain.xml
ruby ../src/convert.rb --check modules/DSL.xml
ruby ../src/convert.rb --check modules/Encoding.xml
ruby ../src/convert.rb --check modules/FileSystems.xml
ruby ../src/convert.rb --check modules/FileUtils.xml
ruby ../src/convert.rb --check modules/FTP.xml
ruby ../src/convert.rb --check modules/GetInstArgs.xml
ruby ../src/convert.rb --check modules/GfxMenu.xml
ruby ../src/convert.rb --check modules/Hooks.xml
ruby ../src/convert.rb --check modules/Hostname.xml
ruby ../src/convert.rb --check modules/Host.xml
ruby ../src/convert.rb --check modules/Hotplug.xml
ruby ../src/convert.rb --check modules/HTML.xml
ruby ../src/convert.rb --check modules/HTTP.xml
ruby ../src/convert.rb --check modules/HWConfig.xml
ruby ../src/convert.rb --check modules/HwStatus.xml
ruby ../src/convert.rb --check modules/Idedma.xml
ruby ../src/convert.rb --check modules/Inetd.xml
ruby ../src/convert.rb --check modules/InitHWinfo.xml
ruby ../src/convert.rb --check modules/Initrd.xml
ruby ../src/convert.rb --check modules/Installation.xml
ruby ../src/convert.rb --check modules/InstShowInfo.xml
ruby ../src/convert.rb --check modules/InstURL.xml
ruby ../src/convert.rb --check modules/Internet.xml
ruby ../src/convert.rb --check modules/IP.xml
ruby ../src/convert.rb --check modules/Irda.xml
ruby ../src/convert.rb --check modules/IscsiClient.xml
ruby ../src/convert.rb --check modules/ISDN.xml
ruby ../src/convert.rb --check modules/Joystick.xml
ruby ../src/convert.rb --check modules/Kerberos.xml
ruby ../src/convert.rb --check modules/Kernel.xml
ruby ../src/convert.rb --check modules/Keyboard.xml
ruby ../src/convert.rb --check modules/Kickstart.xml
ruby ../src/convert.rb --check modules/Label.xml
ruby ../src/convert.rb --check modules/Language.xml
ruby ../src/convert.rb --check modules/Lan.xml
ruby ../src/convert.rb --check modules/LdapPopup.xml
ruby ../src/convert.rb --check modules/Ldap.xml
ruby ../src/convert.rb --check modules/Linuxrc.xml
ruby ../src/convert.rb --check modules/LogView.xml
ruby ../src/convert.rb --check modules/MailAliases.xml
ruby ../src/convert.rb --check modules/Mail.xml
ruby ../src/convert.rb --check modules/Map.xml
ruby ../src/convert.rb --check modules/Message.xml
ruby ../src/convert.rb --check modules/Misc.xml
ruby ../src/convert.rb --check modules/Modem.xml
ruby ../src/convert.rb --check modules/Mode.xml
ruby ../src/convert.rb --check modules/ModuleLoading.xml
ruby ../src/convert.rb --check modules/ModulesComments.xml
ruby ../src/convert.rb --check modules/ModulesConf.xml
ruby ../src/convert.rb --check modules/Mouse.xml
ruby ../src/convert.rb --check modules/Netmask.xml
ruby ../src/convert.rb --check modules/NetworkConfig.xml
ruby ../src/convert.rb --check modules/NetworkDevices.xml
ruby ../src/convert.rb --check modules/NetworkModules.xml
ruby ../src/convert.rb --check modules/NetworkPopup.xml
ruby ../src/convert.rb --check modules/NetworkService.xml
ruby ../src/convert.rb --check modules/NetworkStorage.xml
ruby ../src/convert.rb --check modules/Network.xml
ruby ../src/convert.rb --check modules/NewID.xml
ruby ../src/convert.rb --check modules/Nfs.xml
ruby ../src/convert.rb --check modules/Nis.xml
ruby ../src/convert.rb --check modules/Nsswitch.xml
ruby ../src/convert.rb --check modules/NtpClient.xml
ruby ../src/convert.rb --check modules/OnlineUpdateCallbacks.xml
ruby ../src/convert.rb --check modules/OnlineUpdateDialogs.xml
ruby ../src/convert.rb --check modules/OnlineUpdate.xml
ruby ../src/convert.rb --check modules/OSRBoot.xml
ruby ../src/convert.rb --check modules/OSRCommon.xml
ruby ../src/convert.rb --check modules/OSRDirect.xml
ruby ../src/convert.rb --check modules/OSRExecute.xml
ruby ../src/convert.rb --check modules/OSRFloppy.xml
ruby ../src/convert.rb --check modules/OSRFsck.xml
ruby ../src/convert.rb --check modules/OSRFstab.xml
ruby ../src/convert.rb --check modules/OSRLogFile.xml
ruby ../src/convert.rb --check modules/OSRMode.xml
ruby ../src/convert.rb --check modules/OSRModuleLoading.xml
ruby ../src/convert.rb --check modules/OSRPkgUI.xml
ruby ../src/convert.rb --check modules/OSRPkgVerify.xml
ruby ../src/convert.rb --check modules/OSRPkg.xml
ruby ../src/convert.rb --check modules/OSRPopup.xml
ruby ../src/convert.rb --check modules/OSRProgress.xml
ruby ../src/convert.rb --check modules/OSRPtbl.xml
ruby ../src/convert.rb --check modules/OSRRepairUI.xml
ruby ../src/convert.rb --check modules/OSRStatus.xml
ruby ../src/convert.rb --check modules/OSRSummary.xml
ruby ../src/convert.rb --check modules/OSRSwap.xml
ruby ../src/convert.rb --check modules/OSRSystem.xml
ruby ../src/convert.rb --check modules/OSR.xml
ruby ../src/convert.rb --check modules/PackageAI.xml
ruby ../src/convert.rb --check modules/PackageCallbacksInit.xml
ruby ../src/convert.rb --check modules/PackageCallbacks.xml
ruby ../src/convert.rb --check modules/PackageInstallation.xml
ruby ../src/convert.rb --check modules/PackageLock.xml
ruby ../src/convert.rb --check modules/PackageSelectionIO.xml
ruby ../src/convert.rb --check modules/PackagesUI.xml
ruby ../src/convert.rb --check modules/Packages.xml
ruby ../src/convert.rb --check modules/PackageSystem.xml
ruby ../src/convert.rb --check modules/Package.xml
ruby ../src/convert.rb --check modules/PamSettings.xml
ruby ../src/convert.rb --check modules/Pam.xml
ruby ../src/convert.rb --check modules/Partitions.xml
ruby ../src/convert.rb --check modules/Popup.xml
ruby ../src/convert.rb --check modules/PortAliases.xml
ruby ../src/convert.rb --check modules/PortRanges.xml
ruby ../src/convert.rb --check modules/PowerManagement.xml
ruby ../src/convert.rb --check modules/Printerdb.xml
ruby ../src/convert.rb --check modules/Printerlib.xml
ruby ../src/convert.rb --check modules/PrinterTest.xml
ruby ../src/convert.rb --check modules/Printer.xml
ruby ../src/convert.rb --check modules/ProductControl.xml
ruby ../src/convert.rb --check modules/ProductFeatures.xml
ruby ../src/convert.rb --check modules/ProductLicense.xml
ruby ../src/convert.rb --check modules/Product.xml
ruby ../src/convert.rb --check modules/ProfileLocation.xml
ruby ../src/convert.rb --check modules/ProfileManager.xml
ruby ../src/convert.rb --check modules/Profile.xml
ruby ../src/convert.rb --check modules/Progress.xml
ruby ../src/convert.rb --check modules/Provider.xml
ruby ../src/convert.rb --check modules/Proxy.xml
ruby ../src/convert.rb --check modules/Punycode.xml
ruby ../src/convert.rb --check modules/Register.xml
ruby ../src/convert.rb --check modules/Remote.xml
ruby ../src/convert.rb --check modules/Report.xml
ruby ../src/convert.rb --check modules/Restore.xml
ruby ../src/convert.rb --check modules/RichText.xml
ruby ../src/convert.rb --check modules/RootPart.xml
ruby ../src/convert.rb --check modules/Routing.xml
ruby ../src/convert.rb --check modules/RunlevelEd.xml
ruby ../src/convert.rb --check modules/Runlevel.xml
ruby ../src/convert.rb --check modules/Samba.xml
ruby ../src/convert.rb --check modules/Scanner.xml
ruby ../src/convert.rb --check modules/Security.xml
ruby ../src/convert.rb --check modules/Sequencer.xml
ruby ../src/convert.rb --check modules/Service.xml
ruby ../src/convert.rb --check modules/SignatureCheckCallbacks.xml
ruby ../src/convert.rb --check modules/SignatureCheckDialogs.xml
ruby ../src/convert.rb --check modules/SlideShowCallbacks.xml
ruby ../src/convert.rb --check modules/SlideShow.xml
ruby ../src/convert.rb --check modules/SLP.xml
ruby ../src/convert.rb --check modules/Sound.xml
ruby ../src/convert.rb --check modules/SourceDialogs.xml
ruby ../src/convert.rb --check modules/SourceManagerSLP.xml
ruby ../src/convert.rb --check modules/SourceManager.xml
ruby ../src/convert.rb --check modules/SpaceCalculation.xml
ruby ../src/convert.rb --check modules/Spooler.xml
ruby ../src/convert.rb --check modules/Stage.xml
ruby ../src/convert.rb --check modules/StorageClients.xml
ruby ../src/convert.rb --check modules/StorageControllers.xml
ruby ../src/convert.rb --check modules/StorageDevices.xml
ruby ../src/convert.rb --check modules/Storage.xml
ruby ../src/convert.rb --check modules/String.xml
ruby ../src/convert.rb --check modules/Sudo.xml
ruby ../src/convert.rb --check modules/Summary.xml
ruby ../src/convert.rb --check modules/SuSEFirewall4Network.xml
ruby ../src/convert.rb --check modules/SuSEFirewallCMDLine.xml
ruby ../src/convert.rb --check modules/SuSEFirewallExpertRules.xml
ruby ../src/convert.rb --check modules/SuSEFirewallProposal.xml
ruby ../src/convert.rb --check modules/SuSEFirewallServices.xml
ruby ../src/convert.rb --check modules/SuSEFirewallUI.xml
ruby ../src/convert.rb --check modules/SuSEFirewall.xml
ruby ../src/convert.rb --check modules/SuSERelease.xml
ruby ../src/convert.rb --check modules/Sysconfig.xml
ruby ../src/convert.rb --check modules/SystemFilesCopy.xml
ruby ../src/convert.rb --check modules/SystemSettings.xml
ruby ../src/convert.rb --check modules/TablePopup.xml
ruby ../src/convert.rb --check modules/TFTP.xml
ruby ../src/convert.rb --check modules/Timezone.xml
ruby ../src/convert.rb --check modules/Tv.xml
ruby ../src/convert.rb --check modules/TypeRepository.xml
ruby ../src/convert.rb --check modules/Update.xml
ruby ../src/convert.rb --check modules/URL.xml
ruby ../src/convert.rb --check modules/UsersUI.xml
ruby ../src/convert.rb --check modules/ValueBrowser.xml
ruby ../src/convert.rb --check modules/Vendor.xml
ruby ../src/convert.rb --check modules/Version.xml
ruby ../src/convert.rb --check modules/VM_Common.xml
ruby ../src/convert.rb --check modules/VM_XEN.xml
ruby ../src/convert.rb --check modules/VM.xml
ruby ../src/convert.rb --check modules/Wizard_hw.xml
ruby ../src/convert.rb --check modules/WizardHW.xml
ruby ../src/convert.rb --check modules/Wizard.xml
ruby ../src/convert.rb --check modules/X11Version.xml
ruby ../src/convert.rb --check modules/XMessages.xml
ruby ../src/convert.rb --check modules/XML.xml
ruby ../src/convert.rb --check modules/XVersion.xml
ruby ../src/convert.rb --check modules/Y2ModuleConfig.xml
