#
# Makefile for ycpxml2ruby/tests
#

check: all

all:
	ruby void.rb
	ruby boolean.rb
	ruby integer.rb
	ruby float.rb
	ruby string.rb
	ruby path.rb
	ruby symbol.rb
#	ruby term.rb
	ruby list.rb
	ruby map.rb

	ruby builtin_boolean.rb
	ruby builtin_integer.rb
	ruby builtin_float.rb
	ruby builtin_string.rb

	ruby variable.rb
	ruby if.rb
	ruby bracket_assign.rb
	ruby compare.rb
	ruby yebracket.rb
	ruby triple.rb

	ruby while.rb
	ruby repeat.rb
	ruby do.rb
